// <auto-generated />
using DBConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBConnection.Migrations
{
    [DbContext(typeof(DeliveryContext))]
    [Migration("20210310174529_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBConnection.Models.OrderHead", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DebName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DebName2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DebNo")
                        .HasColumnType("int");

                    b.Property<string>("No")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OrderHead");
                });

            modelBuilder.Entity("DBConnection.Models.OrderLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleDescription2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleDescription3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleNo")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryHeadID")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryHeadNo")
                        .HasColumnType("int");

                    b.Property<string>("LinesID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiptNo")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DeliveryHeadID");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("DBConnection.Models.OrderLine", b =>
                {
                    b.HasOne("DBConnection.Models.OrderHead", "DeliveryHead")
                        .WithMany("OrderLines")
                        .HasForeignKey("DeliveryHeadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
